"""add db relationships

Revision ID: 5774a4668961
Revises: 3c8dfebc4bfa
Create Date: 2024-04-29 16:34:43.129711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5774a4668961'
down_revision = '3c8dfebc4bfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('book_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_reviews_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_reviews_book_id_books'), 'books', ['book_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###
    pass


def downgrade():
    # naming_convention = {
    # "fk":
    # "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    # }
    # with self.op.batch_alter_table(
    #         "bar", naming_convention=naming_convention) as batch_op:
    #     batch_op.drop_constraint(
    #     "fk_bar_foo_id_foo", type_="foreignkey")
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reviews_book_id_books'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_reviews_user_id_users'), type_='foreignkey')
        batch_op.drop_column('book_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
