"""remove first and last name from db

Revision ID: 8edf92fbe59f
Revises: dfdf55c34801
Create Date: 2024-05-21 13:27:52.660642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8edf92fbe59f'
down_revision = 'dfdf55c34801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
